#!/usr/bin/env python
import sys
import os

is_local = os.path.dirname(os.path.realpath(__file__)) == os.getcwd()

import __builtin__
__builtin__.use_local_modules = is_local

if __builtin__.use_local_modules:
    sys.path.insert(0, os.getcwd())

import hashmal_lib

if __name__ == '__main__':
    gui = hashmal_lib.HashmalGui()
    gui.main()
